spring.application.name=Playlist Manager
spring.datasource.url=jdbc:h2:file:./data/playlistdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true




spring.security.user.name=User
spring.security.user.password=password123
spring.security.user.roles=USER

# 2. Utile pour activer la console H2 dans un environnement sécurisé
spring.security.web.header.frame-options=SAMEORIGIN
spring.jpa.open-in-view=true

# 3. Augmenter la verbosité des logs pour le diagnostic
logging.level.org.springframework.security=DEBUG